// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// VCS coverage exclude_file
module regfile_32x32(	// src/main/scala/camp/Core.scala:22:20
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [31:0] R1_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:31];	// src/main/scala/camp/Core.scala:22:20
  always @(posedge W0_clk) begin	// src/main/scala/camp/Core.scala:22:20
    if (W0_en & 1'h1)	// src/main/scala/camp/Core.scala:22:20
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Core.scala:22:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Core.scala:22:20
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Core.scala:22:20
    initial begin	// src/main/scala/camp/Core.scala:22:20
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Core.scala:22:20
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Core.scala:22:20
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Core.scala:22:20
          Memory[i[4:0]] = _RANDOM_MEM;	// src/main/scala/camp/Core.scala:22:20
        end	// src/main/scala/camp/Core.scala:22:20
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/camp/Core.scala:22:20
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// src/main/scala/camp/Core.scala:22:20
endmodule

// VCS coverage exclude_file
module csr_regfile_4096x32(	// src/main/scala/camp/Core.scala:23:24
  input  [11:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [11:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [31:0] R1_data,
  input  [11:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:4095];	// src/main/scala/camp/Core.scala:23:24
  always @(posedge W0_clk) begin	// src/main/scala/camp/Core.scala:23:24
    if (W0_en & 1'h1)	// src/main/scala/camp/Core.scala:23:24
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Core.scala:23:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Core.scala:23:24
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Core.scala:23:24
    initial begin	// src/main/scala/camp/Core.scala:23:24
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Core.scala:23:24
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Core.scala:23:24
        for (logic [12:0] i = 13'h0; i < 13'h1000; i += 13'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Core.scala:23:24
          Memory[i[11:0]] = _RANDOM_MEM;	// src/main/scala/camp/Core.scala:23:24
        end	// src/main/scala/camp/Core.scala:23:24
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/camp/Core.scala:23:24
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// src/main/scala/camp/Core.scala:23:24
endmodule

module Core(	// src/main/scala/camp/Core.scala:8:7
  input         clock,	// src/main/scala/camp/Core.scala:8:7
                reset,	// src/main/scala/camp/Core.scala:8:7
  output [31:0] io_imem_addr,	// src/main/scala/camp/Core.scala:12:14
  input  [31:0] io_imem_inst,	// src/main/scala/camp/Core.scala:12:14
  input         io_imem_valid,	// src/main/scala/camp/Core.scala:12:14
  output [31:0] io_dmem_addr,	// src/main/scala/camp/Core.scala:12:14
  input  [31:0] io_dmem_rdata,	// src/main/scala/camp/Core.scala:12:14
  output        io_dmem_ren,	// src/main/scala/camp/Core.scala:12:14
  input         io_dmem_rvalid,	// src/main/scala/camp/Core.scala:12:14
  output        io_dmem_wen,	// src/main/scala/camp/Core.scala:12:14
  output [3:0]  io_dmem_wstrb,	// src/main/scala/camp/Core.scala:12:14
  output [31:0] io_dmem_wdata,	// src/main/scala/camp/Core.scala:12:14
  output        io_success,	// src/main/scala/camp/Core.scala:12:14
                io_exit,	// src/main/scala/camp/Core.scala:12:14
  output [31:0] io_debug_pc	// src/main/scala/camp/Core.scala:12:14
);

  wire [31:0]      mem_wb_data;	// src/main/scala/chisel3/util/Mux.scala:126:16
  wire             mem_stall_flg;	// src/main/scala/camp/Core.scala:517:32
  wire             exe_jmp_flg;	// src/main/scala/camp/Core.scala:477:34
  wire             exe_br_flg;	// src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      _csr_regfile_ext_R0_data;	// src/main/scala/camp/Core.scala:23:24
  wire [31:0]      _csr_regfile_ext_R1_data;	// src/main/scala/camp/Core.scala:23:24
  wire [31:0]      _regfile_ext_R0_data;	// src/main/scala/camp/Core.scala:22:20
  wire [31:0]      _regfile_ext_R1_data;	// src/main/scala/camp/Core.scala:22:20
  reg  [31:0]      id_reg_pc;	// src/main/scala/camp/Core.scala:29:26
  reg  [31:0]      id_reg_inst;	// src/main/scala/camp/Core.scala:30:28
  reg  [31:0]      exe_reg_pc;	// src/main/scala/camp/Core.scala:33:27
  reg  [4:0]       exe_reg_wb_addr;	// src/main/scala/camp/Core.scala:34:32
  reg  [31:0]      exe_reg_op1_data;	// src/main/scala/camp/Core.scala:35:33
  reg  [31:0]      exe_reg_op2_data;	// src/main/scala/camp/Core.scala:36:33
  reg  [31:0]      exe_reg_rs2_data;	// src/main/scala/camp/Core.scala:37:33
  reg  [4:0]       exe_reg_exe_fun;	// src/main/scala/camp/Core.scala:38:32
  reg  [1:0]       exe_reg_mem_wen;	// src/main/scala/camp/Core.scala:39:32
  reg  [1:0]       exe_reg_rf_wen;	// src/main/scala/camp/Core.scala:40:31
  reg  [2:0]       exe_reg_wb_sel;	// src/main/scala/camp/Core.scala:41:31
  reg  [11:0]      exe_reg_csr_addr;	// src/main/scala/camp/Core.scala:42:33
  reg  [2:0]       exe_reg_csr_cmd;	// src/main/scala/camp/Core.scala:43:32
  reg  [31:0]      exe_reg_imm_b_sext;	// src/main/scala/camp/Core.scala:46:35
  reg  [31:0]      exe_reg_mem_w;	// src/main/scala/camp/Core.scala:49:30
  reg  [31:0]      mem_reg_pc;	// src/main/scala/camp/Core.scala:52:27
  reg  [4:0]       mem_reg_wb_addr;	// src/main/scala/camp/Core.scala:53:32
  reg  [31:0]      mem_reg_op1_data;	// src/main/scala/camp/Core.scala:54:33
  reg  [31:0]      mem_reg_rs2_data;	// src/main/scala/camp/Core.scala:55:33
  reg  [1:0]       mem_reg_mem_wen;	// src/main/scala/camp/Core.scala:56:32
  reg  [1:0]       mem_reg_rf_wen;	// src/main/scala/camp/Core.scala:57:31
  reg  [2:0]       mem_reg_wb_sel;	// src/main/scala/camp/Core.scala:58:31
  reg  [11:0]      mem_reg_csr_addr;	// src/main/scala/camp/Core.scala:59:33
  reg  [2:0]       mem_reg_csr_cmd;	// src/main/scala/camp/Core.scala:60:32
  reg  [31:0]      mem_reg_alu_out;	// src/main/scala/camp/Core.scala:62:32
  reg  [31:0]      mem_reg_mem_w;	// src/main/scala/camp/Core.scala:63:30
  reg  [3:0]       mem_reg_mem_wstrb;	// src/main/scala/camp/Core.scala:64:34
  reg  [4:0]       wb_reg_wb_addr;	// src/main/scala/camp/Core.scala:67:31
  reg  [1:0]       wb_reg_rf_wen;	// src/main/scala/camp/Core.scala:68:30
  reg  [31:0]      wb_reg_wb_data;	// src/main/scala/camp/Core.scala:69:31
  reg  [31:0]      if_reg_pc;	// src/main/scala/camp/Core.scala:74:26
  wire [31:0]      if_inst = io_imem_valid ? io_imem_inst : 32'h13;	// src/main/scala/camp/Core.scala:76:20
  wire             _id_inst_T = exe_br_flg | exe_jmp_flg;	// src/main/scala/camp/Core.scala:105:19, :477:34, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _id_rs2_data_hazard_T = exe_reg_rf_wen == 2'h1;	// src/main/scala/camp/Core.scala:40:31, :119:21
  wire             stall_flg =
    _id_rs2_data_hazard_T & (|(id_reg_inst[19:15]))
    & id_reg_inst[19:15] == exe_reg_wb_addr | _id_rs2_data_hazard_T
    & (|(id_reg_inst[24:20])) & id_reg_inst[24:20] == exe_reg_wb_addr | mem_stall_flg;	// src/main/scala/camp/Core.scala:30:28, :34:32, :114:34, :115:34, :119:{21,50,59,77}, :121:{50,59,77}, :122:58, :517:32
  wire [31:0]      id_inst = _id_inst_T | stall_flg ? 32'h13 : id_reg_inst;	// src/main/scala/camp/Core.scala:30:28, :76:20, :105:19, :122:58, :126:{8,36}
  wire             _id_rs2_data_T_2 = mem_reg_rf_wen == 2'h1;	// src/main/scala/camp/Core.scala:57:31, :119:21, :137:61
  wire             _id_rs2_data_T_5 = wb_reg_rf_wen == 2'h1;	// src/main/scala/camp/Core.scala:68:30, :119:21, :138:59
  wire [31:0]      id_rs1_data =
    id_inst[19:15] == 5'h0
      ? 32'h0
      : id_inst[19:15] == mem_reg_wb_addr & _id_rs2_data_T_2
          ? mem_wb_data
          : id_inst[19:15] == wb_reg_wb_addr & _id_rs2_data_T_5
              ? wb_reg_wb_data
              : _regfile_ext_R1_data;	// src/main/scala/camp/Core.scala:8:7, :22:20, :29:26, :53:32, :67:31, :69:31, :126:8, :128:28, :136:20, :137:{21,42,61}, :138:{21,41,59}, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      id_rs2_data =
    id_inst[24:20] == 5'h0
      ? 32'h0
      : id_inst[24:20] == mem_reg_wb_addr & _id_rs2_data_T_2
          ? mem_wb_data
          : id_inst[24:20] == wb_reg_wb_addr & _id_rs2_data_T_5
              ? wb_reg_wb_data
              : _regfile_ext_R0_data;	// src/main/scala/camp/Core.scala:8:7, :22:20, :29:26, :53:32, :67:31, :69:31, :126:8, :129:28, :137:61, :138:59, :144:20, :145:{21,42}, :146:{21,41}, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      _exe_alu_out_T_31 = exe_reg_op1_data + exe_reg_op2_data;	// src/main/scala/camp/Core.scala:35:33, :36:33, :438:58
  wire [62:0]      _exe_alu_out_T_14 = {31'h0, exe_reg_op1_data} << exe_reg_op2_data[4:0];	// src/main/scala/camp/Core.scala:35:33, :36:33, :443:{58,77}
  wire [31:0]      _GEN = {27'h0, exe_reg_op2_data[4:0]};	// src/main/scala/camp/Core.scala:36:33, :161:31, :443:77, :447:58
  wire             _exe_br_flg_T_17 = exe_reg_op1_data < exe_reg_op2_data;	// src/main/scala/camp/Core.scala:35:33, :36:33, :456:59
  wire [31:0]      exe_alu_out =
    exe_reg_exe_fun == 5'h1
      ? _exe_alu_out_T_31
      : exe_reg_exe_fun == 5'h2
          ? exe_reg_op1_data - exe_reg_op2_data
          : exe_reg_exe_fun == 5'h3
              ? exe_reg_op1_data & exe_reg_op2_data
              : exe_reg_exe_fun == 5'h4
                  ? exe_reg_op1_data | exe_reg_op2_data
                  : exe_reg_exe_fun == 5'h5
                      ? exe_reg_op1_data ^ exe_reg_op2_data
                      : exe_reg_exe_fun == 5'h6
                          ? _exe_alu_out_T_14[31:0]
                          : exe_reg_exe_fun == 5'h7
                              ? exe_reg_op1_data >> _GEN
                              : exe_reg_exe_fun == 5'h8
                                  ? $signed($signed(exe_reg_op1_data) >>> _GEN)
                                  : exe_reg_exe_fun == 5'h9
                                      ? {31'h0,
                                         $signed(exe_reg_op1_data) < $signed(exe_reg_op2_data)}
                                      : exe_reg_exe_fun == 5'hA
                                          ? {31'h0, _exe_br_flg_T_17}
                                          : exe_reg_exe_fun == 5'h11
                                              ? _exe_alu_out_T_31 & 32'hFFFFFFFE
                                              : exe_reg_exe_fun == 5'h12
                                                  ? exe_reg_op1_data
                                                  : 32'h0;	// src/main/scala/camp/Core.scala:8:7, :29:26, :35:33, :36:33, :38:32, :438:{24,58}, :439:{24,58}, :440:{24,58}, :441:{24,57}, :442:{24,58}, :443:{24,58}, :446:9, :447:{24,58}, :451:{24,65}, :455:{24,65}, :456:{24,59}, :457:{24,80,82}, :459:24, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _exe_br_flg_T_3 = exe_reg_op1_data == exe_reg_op2_data;	// src/main/scala/camp/Core.scala:35:33, :36:33, :467:57
  assign exe_br_flg =
    exe_reg_exe_fun == 5'hB
      ? _exe_br_flg_T_3
      : exe_reg_exe_fun == 5'hC
          ? ~_exe_br_flg_T_3
          : exe_reg_exe_fun == 5'hD
              ? $signed(exe_reg_op1_data) < $signed(exe_reg_op2_data)
              : exe_reg_exe_fun == 5'hE
                  ? $signed(exe_reg_op1_data) >= $signed(exe_reg_op2_data)
                  : exe_reg_exe_fun == 5'hF
                      ? _exe_br_flg_T_17
                      : exe_reg_exe_fun == 5'h10 & ~_exe_br_flg_T_17;	// src/main/scala/camp/Core.scala:8:7, :35:33, :36:33, :38:32, :456:59, :467:{24,57}, :468:{24,39}, :469:{24,64}, :470:{24,65}, :471:24, :472:{24,40}, src/main/scala/chisel3/util/Mux.scala:126:16
  assign exe_jmp_flg = exe_reg_wb_sel == 3'h2;	// src/main/scala/camp/Core.scala:41:31, :477:34, src/main/scala/chisel3/util/Lookup.scala:34:39
  wire             io_dmem_ren_0 = mem_reg_wb_sel == 3'h1;	// src/main/scala/camp/Core.scala:58:31, :509:33, src/main/scala/chisel3/util/Lookup.scala:34:39
  wire [94:0]      _io_dmem_wdata_T_2 =
    {63'h0, mem_reg_rs2_data} << {90'h0, mem_reg_alu_out[1:0], 3'h0};	// src/main/scala/camp/Core.scala:41:31, :55:33, :62:32, :512:{38,63}
  assign mem_stall_flg = io_dmem_ren_0 & ~io_dmem_rvalid;	// src/main/scala/camp/Core.scala:509:33, :517:{32,35}
  wire [31:0]      mem_wb_rdata = io_dmem_rdata >> {27'h0, mem_reg_alu_out[1:0], 3'h0};	// src/main/scala/camp/Core.scala:41:31, :62:32, :161:31, :512:63, :545:19
  assign mem_wb_data =
    io_dmem_ren_0
      ? (mem_reg_mem_w == 32'h3
           ? {{24{mem_wb_rdata[7]}}, mem_wb_rdata[7:0]}
           : mem_reg_mem_w == 32'h2
               ? {{16{mem_wb_rdata[15]}}, mem_wb_rdata[15:0]}
               : mem_reg_mem_w == 32'h5
                   ? {24'h0, mem_wb_rdata[7:0]}
                   : mem_reg_mem_w == 32'h4 ? {16'h0, mem_wb_rdata[15:0]} : mem_wb_rdata)
      : mem_reg_wb_sel == 3'h2
          ? mem_reg_pc + 32'h4
          : mem_reg_wb_sel == 3'h3 ? _csr_regfile_ext_R1_data : mem_reg_alu_out;	// src/main/scala/camp/Core.scala:23:24, :52:27, :58:31, :62:32, :63:30, :499:24, :509:33, :538:{9,29,38,46}, :541:29, :545:19, :549:22, :550:22, :554:22, :555:22, :566:{23,49}, :567:23, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
  reg              successDetected;	// src/main/scala/camp/Core.scala:590:32
  `ifndef SYNTHESIS	// src/main/scala/camp/Core.scala:600:11
    always @(posedge clock) begin	// src/main/scala/camp/Core.scala:600:11
      if ((`PRINTF_COND_) & ~reset) begin	// src/main/scala/camp/Core.scala:600:11, :614:11
        $fwrite(32'h80000002, "if_reg_pc        : 0x%x\n", if_reg_pc);	// src/main/scala/camp/Core.scala:74:26, :600:11
        $fwrite(32'h80000002, "id_reg_pc        : 0x%x\n", id_reg_pc);	// src/main/scala/camp/Core.scala:29:26, :600:11, :601:11
        $fwrite(32'h80000002, "id_reg_inst      : 0x%x\n", id_reg_inst);	// src/main/scala/camp/Core.scala:30:28, :600:11, :602:11
        $fwrite(32'h80000002, "stall_flg        : 0x%x\n", stall_flg);	// src/main/scala/camp/Core.scala:122:58, :600:11, :603:11
        $fwrite(32'h80000002, "id_inst          : 0x%x\n", id_inst);	// src/main/scala/camp/Core.scala:126:8, :600:11, :604:11
        $fwrite(32'h80000002, "id_rs1_data      : 0x%x\n", id_rs1_data);	// src/main/scala/camp/Core.scala:600:11, :605:11, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "id_rs2_data      : 0x%x\n", id_rs2_data);	// src/main/scala/camp/Core.scala:600:11, :606:11, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "exe_reg_pc       : 0x%x\n", exe_reg_pc);	// src/main/scala/camp/Core.scala:33:27, :600:11, :607:11
        $fwrite(32'h80000002, "exe_reg_op1_data : 0x%x\n", exe_reg_op1_data);	// src/main/scala/camp/Core.scala:35:33, :600:11, :608:11
        $fwrite(32'h80000002, "exe_reg_op2_data : 0x%x\n", exe_reg_op2_data);	// src/main/scala/camp/Core.scala:36:33, :600:11, :609:11
        $fwrite(32'h80000002, "exe_alu_out      : 0x%x\n", exe_alu_out);	// src/main/scala/camp/Core.scala:600:11, :610:11, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "mem_reg_pc       : 0x%x\n", mem_reg_pc);	// src/main/scala/camp/Core.scala:52:27, :600:11, :611:11
        $fwrite(32'h80000002, "mem_wb_data      : 0x%x\n", mem_wb_data);	// src/main/scala/camp/Core.scala:600:11, :612:11, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "wb_reg_wb_data   : 0x%x\n", wb_reg_wb_data);	// src/main/scala/camp/Core.scala:69:31, :600:11, :613:11
        $fwrite(32'h80000002, "---------\n");	// src/main/scala/camp/Core.scala:600:11, :614:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [9:0]       _GEN_0 = {id_inst[14:12], id_inst[6:0]};	// src/main/scala/camp/Core.scala:126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_1 = _GEN_0 == 10'h3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_3 = _GEN_0 == 10'h203;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_5 = _GEN_0 == 10'h23;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_7 = _GEN_0 == 10'h83;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_9 = _GEN_0 == 10'h283;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_11 = _GEN_0 == 10'hA3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_13 = _GEN_0 == 10'h103;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_15 = _GEN_0 == 10'h123;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [16:0]      _GEN_1 = {id_inst[31:25], id_inst[14:12], id_inst[6:0]};	// src/main/scala/camp/Core.scala:126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_17 = _GEN_1 == 17'h33;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_19 = _GEN_0 == 10'h13;	// src/main/scala/camp/Core.scala:76:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_21 = _GEN_1 == 17'h8033;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_23 = _GEN_1 == 17'h3B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_25 = _GEN_1 == 17'h333;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_27 = _GEN_1 == 17'h233;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_29 = _GEN_0 == 10'h393;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_31 = _GEN_0 == 10'h313;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_33 = _GEN_0 == 10'h213;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_35 = _GEN_1 == 17'hB3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_37 = _GEN_1 == 17'h2B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_39 = _GEN_1 == 17'h82B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_41 = _GEN_1 == 17'h93;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_43 = _GEN_1 == 17'h293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_45 = _GEN_1 == 17'h8293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_47 = _GEN_1 == 17'h133;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_49 = _GEN_1 == 17'h1B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_51 = _GEN_0 == 10'h113;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_53 = _GEN_0 == 10'h193;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_55 = _GEN_0 == 10'h63;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_57 = _GEN_0 == 10'hE3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_59 = _GEN_0 == 10'h2E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_61 = _GEN_0 == 10'h3E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_63 = _GEN_0 == 10'h263;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_65 = _GEN_0 == 10'h363;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_67 = id_inst[6:0] == 7'h6F;	// src/main/scala/camp/Core.scala:126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_69 = _GEN_0 == 10'h67;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_71 = id_inst[6:0] == 7'h37;	// src/main/scala/camp/Core.scala:126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_73 = id_inst[6:0] == 7'h17;	// src/main/scala/camp/Core.scala:126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_75 = _GEN_0 == 10'hF3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_77 = _GEN_0 == 10'h2F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_79 = _GEN_0 == 10'h173;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_81 = _GEN_0 == 10'h373;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_83 = _GEN_0 == 10'h1F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_85 = _GEN_0 == 10'h3F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_87 = id_inst == 32'h73;	// src/main/scala/camp/Core.scala:92:16, :126:8, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _GEN_2 = _csignals_T_83 | _csignals_T_85;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_3 =
    _csignals_T_75 | _csignals_T_77 | _csignals_T_79 | _csignals_T_81 | _GEN_2;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_4 = _csignals_T_71 | _csignals_T_73;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_5 =
    _csignals_T_55 | _csignals_T_57 | _csignals_T_59 | _csignals_T_61 | _csignals_T_63
    | _csignals_T_65;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_6 =
    _csignals_T_15 | _csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23
    | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33
    | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43
    | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53
    | _GEN_5;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_7 = _csignals_T_51 | _csignals_T_53;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_8 = _csignals_T_7 | _csignals_T_9;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_9 = _csignals_T_1 | _csignals_T_3;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [2:0]       csignals_6 =
    _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9
    | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19
    | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29
    | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39
    | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49
    | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _csignals_T_59
    | _csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69
    | _GEN_4
      ? 3'h0
      : _csignals_T_75 | _csignals_T_77
          ? 3'h1
          : _csignals_T_79 | _csignals_T_81
              ? 3'h2
              : _GEN_2 ? 3'h3 : {_csignals_T_87, 2'h0};	// src/main/scala/camp/Core.scala:39:32, :41:31, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [3:0][31:0] _GEN_10 =
    {{{27'h0, id_inst[19:15]}}, {32'h0}, {id_reg_pc}, {id_rs1_data}};	// src/main/scala/camp/Core.scala:29:26, :126:8, :128:28, :161:{26,31}, :390:19, :391:19, :392:19, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [7:0][31:0] _GEN_11 =
    {{32'h0},
     {32'h0},
     {{id_inst[31:12], 12'h0}},
     {{{12{id_inst[31]}}, id_inst[19:12], id_inst[20], id_inst[30:21], 1'h0}},
     {{{20{id_inst[31]}}, id_inst[31:25], id_inst[11:7]}},
     {{{20{id_inst[31]}}, id_inst[31:20]}},
     {id_rs2_data},
     {32'h0}};	// src/main/scala/camp/Core.scala:8:7, :29:26, :42:33, :126:8, :130:27, :150:25, :151:{26,31,44}, :152:29, :153:{26,31,44}, :154:29, :156:{42,59,72}, :157:26, :158:25, :159:29, :398:19, :399:19, :400:19, :401:19, :402:19, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [6:0]       _mem_reg_mem_wstrb_T_7 =
    {3'h0, exe_reg_mem_w == 32'h3 ? 4'h1 : exe_reg_mem_w == 32'h2 ? 4'h3 : 4'hF}
    << exe_alu_out[1:0];	// src/main/scala/camp/Core.scala:41:31, :49:30, :498:24, :499:24, :502:{7,22}, src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/chisel3/util/Mux.scala:126:16
  always @(posedge clock) begin	// src/main/scala/camp/Core.scala:8:7
    if (reset) begin	// src/main/scala/camp/Core.scala:8:7
      id_reg_pc <= 32'h0;	// src/main/scala/camp/Core.scala:29:26
      id_reg_inst <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :30:28
      exe_reg_pc <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :33:27
      exe_reg_wb_addr <= 5'h0;	// src/main/scala/camp/Core.scala:8:7, :34:32
      exe_reg_op1_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :35:33
      exe_reg_op2_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :36:33
      exe_reg_rs2_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :37:33
      exe_reg_exe_fun <= 5'h0;	// src/main/scala/camp/Core.scala:8:7, :38:32
      exe_reg_mem_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32
      exe_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :40:31
      exe_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31
      exe_reg_csr_addr <= 12'h0;	// src/main/scala/camp/Core.scala:42:33
      exe_reg_csr_cmd <= 3'h0;	// src/main/scala/camp/Core.scala:41:31, :43:32
      exe_reg_imm_b_sext <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :46:35
      exe_reg_mem_w <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :49:30
      mem_reg_pc <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :52:27
      mem_reg_wb_addr <= 5'h0;	// src/main/scala/camp/Core.scala:8:7, :53:32
      mem_reg_op1_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :54:33
      mem_reg_rs2_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :55:33
      mem_reg_mem_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :56:32
      mem_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :57:31
      mem_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31, :58:31
      mem_reg_csr_addr <= 12'h0;	// src/main/scala/camp/Core.scala:42:33, :59:33
      mem_reg_csr_cmd <= 3'h0;	// src/main/scala/camp/Core.scala:41:31, :60:32
      mem_reg_alu_out <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :62:32
      mem_reg_mem_w <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :63:30
      mem_reg_mem_wstrb <= 4'h0;	// src/main/scala/camp/Core.scala:64:34
      wb_reg_wb_addr <= 5'h0;	// src/main/scala/camp/Core.scala:8:7, :67:31
      wb_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :68:30
      wb_reg_wb_data <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :69:31
      if_reg_pc <= 32'h0;	// src/main/scala/camp/Core.scala:29:26, :74:26
      successDetected <= 1'h0;	// src/main/scala/camp/Core.scala:8:7, :590:32
    end
    else begin	// src/main/scala/camp/Core.scala:8:7
      if (~stall_flg)	// src/main/scala/camp/Core.scala:122:58
        id_reg_pc <= if_reg_pc;	// src/main/scala/camp/Core.scala:29:26, :74:26
      if (_id_inst_T)	// src/main/scala/camp/Core.scala:105:19
        id_reg_inst <= 32'h13;	// src/main/scala/camp/Core.scala:30:28, :76:20
      else if (~stall_flg)	// src/main/scala/camp/Core.scala:122:58
        id_reg_inst <= if_inst;	// src/main/scala/camp/Core.scala:30:28, :76:20
      if (~mem_stall_flg) begin	// src/main/scala/camp/Core.scala:517:32
        exe_reg_pc <= id_reg_pc;	// src/main/scala/camp/Core.scala:29:26, :33:27
        exe_reg_wb_addr <= id_inst[11:7];	// src/main/scala/camp/Core.scala:34:32, :126:8, :130:27
        exe_reg_op1_data <=
          _GEN_10[_csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7
                  | _csignals_T_9 | _csignals_T_11 | _csignals_T_13 | _GEN_6
                    ? 2'h0
                    : _csignals_T_67
                        ? 2'h1
                        : _csignals_T_69
                            ? 2'h0
                            : _csignals_T_71
                                ? 2'h2
                                : _csignals_T_73
                                    ? 2'h1
                                    : _csignals_T_75
                                        ? 2'h0
                                        : _csignals_T_77
                                            ? 2'h3
                                            : _csignals_T_79
                                                ? 2'h0
                                                : _csignals_T_81
                                                    ? 2'h3
                                                    : _csignals_T_83
                                                        ? 2'h0
                                                        : _csignals_T_85
                                                            ? 2'h3
                                                            : {_csignals_T_87, 1'h0}];	// src/main/scala/camp/Core.scala:8:7, :35:33, :39:32, :119:21, :390:19, :391:19, :392:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
        exe_reg_op2_data <=
          _GEN_11[_GEN_9
                    ? 3'h2
                    : _csignals_T_5
                        ? 3'h3
                        : _GEN_8
                            ? 3'h2
                            : _csignals_T_11
                                ? 3'h3
                                : _csignals_T_13
                                    ? 3'h2
                                    : _csignals_T_15
                                        ? 3'h3
                                        : _csignals_T_17
                                            ? 3'h1
                                            : _csignals_T_19
                                                ? 3'h2
                                                : _csignals_T_21 | _csignals_T_23
                                                  | _csignals_T_25 | _csignals_T_27
                                                    ? 3'h1
                                                    : _csignals_T_29 | _csignals_T_31
                                                      | _csignals_T_33
                                                        ? 3'h2
                                                        : _csignals_T_35 | _csignals_T_37
                                                          | _csignals_T_39
                                                            ? 3'h1
                                                            : _csignals_T_41
                                                              | _csignals_T_43
                                                              | _csignals_T_45
                                                                ? 3'h2
                                                                : _csignals_T_47
                                                                  | _csignals_T_49
                                                                    ? 3'h1
                                                                    : _GEN_7
                                                                        ? 3'h2
                                                                        : _GEN_5
                                                                            ? 3'h1
                                                                            : _csignals_T_67
                                                                                ? 3'h4
                                                                                : _csignals_T_69
                                                                                    ? 3'h2
                                                                                    : _GEN_4
                                                                                        ? 3'h5
                                                                                        : {2'h0,
                                                                                           ~(_csignals_T_75
                                                                                             | _csignals_T_77
                                                                                             | _csignals_T_79
                                                                                             | _csignals_T_81
                                                                                             | _csignals_T_83
                                                                                             | _csignals_T_85
                                                                                             | _csignals_T_87)}];	// src/main/scala/camp/Core.scala:36:33, :39:32, :398:19, :399:19, :400:19, :401:19, :402:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
        exe_reg_rs2_data <= id_rs2_data;	// src/main/scala/camp/Core.scala:37:33, src/main/scala/chisel3/util/Mux.scala:126:16
        if (_csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9
            | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17
            | _csignals_T_19)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
          exe_reg_exe_fun <= 5'h1;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_21)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h2;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_23)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h3;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_25)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h4;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_27)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h5;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_29)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h3;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_31)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h4;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_33)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h5;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_35)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h6;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_37)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h7;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_39)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h8;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_41)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h6;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_43)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h7;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_45)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h8;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_47)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h9;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_49)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hA;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_51)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h9;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_53)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hA;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_55)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hB;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_57)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hC;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_59)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hE;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_61)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h10;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_63)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hD;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_65)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'hF;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_67)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h1;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_csignals_T_69)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_exe_fun <= 5'h11;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_GEN_4)	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_exe_fun <= 5'h1;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else if (_GEN_3)	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_exe_fun <= 5'h12;	// src/main/scala/camp/Core.scala:8:7, :38:32
        else	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_exe_fun <= 5'h0;	// src/main/scala/camp/Core.scala:8:7, :38:32
        exe_reg_mem_wen <=
          _GEN_9
            ? 2'h0
            : _csignals_T_5
                ? 2'h1
                : _GEN_8
                    ? 2'h0
                    : _csignals_T_11
                        ? 2'h1
                        : _csignals_T_13 ? 2'h0 : {1'h0, _csignals_T_15};	// src/main/scala/camp/Core.scala:8:7, :39:32, :119:21, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
        if (_GEN_9) begin	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_rf_wen <= 2'h1;	// src/main/scala/camp/Core.scala:40:31, :119:21
          exe_reg_wb_sel <= 3'h1;	// src/main/scala/camp/Core.scala:41:31, src/main/scala/chisel3/util/Lookup.scala:34:39
        end
        else if (_csignals_T_5) begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :40:31
          exe_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31
        end
        else if (_GEN_8) begin	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_rf_wen <= 2'h1;	// src/main/scala/camp/Core.scala:40:31, :119:21
          exe_reg_wb_sel <= 3'h1;	// src/main/scala/camp/Core.scala:41:31, src/main/scala/chisel3/util/Lookup.scala:34:39
        end
        else if (_csignals_T_11) begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :40:31
          exe_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31
        end
        else if (_csignals_T_13) begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_rf_wen <= 2'h1;	// src/main/scala/camp/Core.scala:40:31, :119:21
          exe_reg_wb_sel <= 3'h1;	// src/main/scala/camp/Core.scala:41:31, src/main/scala/chisel3/util/Lookup.scala:34:39
        end
        else begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
          if (_csignals_T_15)	// src/main/scala/chisel3/util/Lookup.scala:31:38
            exe_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :40:31
          else if (_csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23
                   | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31
                   | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39
                   | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47
                   | _csignals_T_49 | _GEN_7)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
            exe_reg_rf_wen <= 2'h1;	// src/main/scala/camp/Core.scala:40:31, :119:21
          else if (_GEN_5)	// src/main/scala/chisel3/util/Lookup.scala:34:39
            exe_reg_rf_wen <= 2'h0;	// src/main/scala/camp/Core.scala:39:32, :40:31
          else	// src/main/scala/chisel3/util/Lookup.scala:34:39
            exe_reg_rf_wen <=
              {1'h0,
               _csignals_T_67 | _csignals_T_69 | _csignals_T_71 | _csignals_T_73
                 | _GEN_3};	// src/main/scala/camp/Core.scala:8:7, :40:31, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
          if (_GEN_6)	// src/main/scala/chisel3/util/Lookup.scala:34:39
            exe_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31
          else if (_csignals_T_67 | _csignals_T_69)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
            exe_reg_wb_sel <= 3'h2;	// src/main/scala/camp/Core.scala:41:31, src/main/scala/chisel3/util/Lookup.scala:34:39
          else if (_GEN_4 | ~_GEN_3)	// src/main/scala/chisel3/util/Lookup.scala:34:39
            exe_reg_wb_sel <= 3'h0;	// src/main/scala/camp/Core.scala:41:31
          else	// src/main/scala/chisel3/util/Lookup.scala:34:39
            exe_reg_wb_sel <= 3'h3;	// src/main/scala/camp/Core.scala:41:31, src/main/scala/chisel3/util/Lookup.scala:34:39
        end
        exe_reg_csr_addr <= csignals_6 == 3'h4 ? 12'h342 : id_inst[31:20];	// src/main/scala/camp/Core.scala:42:33, :126:8, :150:25, :407:{8,20}, src/main/scala/chisel3/util/Lookup.scala:34:39
        exe_reg_csr_cmd <= csignals_6;	// src/main/scala/camp/Core.scala:43:32, src/main/scala/chisel3/util/Lookup.scala:34:39
        exe_reg_imm_b_sext <=
          {{20{id_inst[31]}}, id_inst[7], id_inst[30:25], id_inst[11:8], 1'h0};	// src/main/scala/camp/Core.scala:8:7, :46:35, :126:8, :154:{29,42,54,71}, :155:26
        exe_reg_mem_w <=
          {29'h0,
           _csignals_T_1
             ? 3'h3
             : _csignals_T_3
                 ? 3'h5
                 : _csignals_T_5
                     ? 3'h3
                     : _csignals_T_7
                         ? 3'h2
                         : _csignals_T_9
                             ? 3'h4
                             : _csignals_T_11
                                 ? 3'h2
                                 : {2'h0, _csignals_T_13 | _csignals_T_15}};	// src/main/scala/camp/Core.scala:39:32, :49:30, :429:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
        mem_reg_pc <= exe_reg_pc;	// src/main/scala/camp/Core.scala:33:27, :52:27
        mem_reg_wb_addr <= exe_reg_wb_addr;	// src/main/scala/camp/Core.scala:34:32, :53:32
        mem_reg_op1_data <= exe_reg_op1_data;	// src/main/scala/camp/Core.scala:35:33, :54:33
        mem_reg_rs2_data <= exe_reg_rs2_data;	// src/main/scala/camp/Core.scala:37:33, :55:33
        mem_reg_mem_wen <= exe_reg_mem_wen;	// src/main/scala/camp/Core.scala:39:32, :56:32
        mem_reg_rf_wen <= exe_reg_rf_wen;	// src/main/scala/camp/Core.scala:40:31, :57:31
        mem_reg_wb_sel <= exe_reg_wb_sel;	// src/main/scala/camp/Core.scala:41:31, :58:31
        mem_reg_csr_addr <= exe_reg_csr_addr;	// src/main/scala/camp/Core.scala:42:33, :59:33
        mem_reg_csr_cmd <= exe_reg_csr_cmd;	// src/main/scala/camp/Core.scala:43:32, :60:32
        mem_reg_alu_out <= exe_alu_out;	// src/main/scala/camp/Core.scala:62:32, src/main/scala/chisel3/util/Mux.scala:126:16
        mem_reg_mem_w <= exe_reg_mem_w;	// src/main/scala/camp/Core.scala:49:30, :63:30
        mem_reg_mem_wstrb <= _mem_reg_mem_wstrb_T_7[3:0];	// src/main/scala/camp/Core.scala:64:34, :502:{7,30}
      end
      wb_reg_wb_addr <= mem_reg_wb_addr;	// src/main/scala/camp/Core.scala:53:32, :67:31
      wb_reg_rf_wen <= mem_stall_flg ? 2'h0 : mem_reg_rf_wen;	// src/main/scala/camp/Core.scala:39:32, :57:31, :68:30, :517:32, :574:23
      wb_reg_wb_data <= mem_wb_data;	// src/main/scala/camp/Core.scala:69:31, src/main/scala/chisel3/util/Mux.scala:126:16
      if (exe_br_flg)	// src/main/scala/chisel3/util/Mux.scala:126:16
        if_reg_pc <= exe_reg_pc + exe_reg_imm_b_sext;	// src/main/scala/camp/Core.scala:33:27, :46:35, :74:26, :475:31
      else if (exe_jmp_flg)	// src/main/scala/camp/Core.scala:477:34
        if_reg_pc <= exe_alu_out;	// src/main/scala/camp/Core.scala:74:26, src/main/scala/chisel3/util/Mux.scala:126:16
      else if (if_inst == 32'h73)	// src/main/scala/camp/Core.scala:76:20, :92:16
        if_reg_pc <= _csr_regfile_ext_R0_data;	// src/main/scala/camp/Core.scala:23:24, :74:26
      else if (~(stall_flg | ~io_imem_valid))	// src/main/scala/camp/Core.scala:93:{18,21}, :122:58
        if_reg_pc <= if_reg_pc + 32'h4;	// src/main/scala/camp/Core.scala:74:26, :85:31, :555:22
      if (~(if_inst == 32'h13))	// src/main/scala/camp/Core.scala:76:20, :591:25, :592:13
        successDetected <= if_inst == 32'h513;	// src/main/scala/camp/Core.scala:76:20, :590:32, :593:13
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/camp/Core.scala:8:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/Core.scala:8:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/Core.scala:8:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:22];	// src/main/scala/camp/Core.scala:8:7
    initial begin	// src/main/scala/camp/Core.scala:8:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/camp/Core.scala:8:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Core.scala:8:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Core.scala:8:7
        for (logic [4:0] i = 5'h0; i < 5'h17; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/camp/Core.scala:8:7
        end	// src/main/scala/camp/Core.scala:8:7
        id_reg_pc = _RANDOM[5'h0];	// src/main/scala/camp/Core.scala:8:7, :29:26
        id_reg_inst = _RANDOM[5'h1];	// src/main/scala/camp/Core.scala:8:7, :30:28
        exe_reg_pc = _RANDOM[5'h2];	// src/main/scala/camp/Core.scala:8:7, :33:27
        exe_reg_wb_addr = _RANDOM[5'h3][4:0];	// src/main/scala/camp/Core.scala:8:7, :34:32
        exe_reg_op1_data = {_RANDOM[5'h3][31:5], _RANDOM[5'h4][4:0]};	// src/main/scala/camp/Core.scala:8:7, :34:32, :35:33
        exe_reg_op2_data = {_RANDOM[5'h4][31:5], _RANDOM[5'h5][4:0]};	// src/main/scala/camp/Core.scala:8:7, :35:33, :36:33
        exe_reg_rs2_data = {_RANDOM[5'h5][31:5], _RANDOM[5'h6][4:0]};	// src/main/scala/camp/Core.scala:8:7, :36:33, :37:33
        exe_reg_exe_fun = _RANDOM[5'h6][9:5];	// src/main/scala/camp/Core.scala:8:7, :37:33, :38:32
        exe_reg_mem_wen = _RANDOM[5'h6][11:10];	// src/main/scala/camp/Core.scala:8:7, :37:33, :39:32
        exe_reg_rf_wen = _RANDOM[5'h6][13:12];	// src/main/scala/camp/Core.scala:8:7, :37:33, :40:31
        exe_reg_wb_sel = _RANDOM[5'h6][16:14];	// src/main/scala/camp/Core.scala:8:7, :37:33, :41:31
        exe_reg_csr_addr = _RANDOM[5'h6][28:17];	// src/main/scala/camp/Core.scala:8:7, :37:33, :42:33
        exe_reg_csr_cmd = _RANDOM[5'h6][31:29];	// src/main/scala/camp/Core.scala:8:7, :37:33, :43:32
        exe_reg_imm_b_sext = _RANDOM[5'h9];	// src/main/scala/camp/Core.scala:8:7, :46:35
        exe_reg_mem_w = _RANDOM[5'hC];	// src/main/scala/camp/Core.scala:8:7, :49:30
        mem_reg_pc = _RANDOM[5'hD];	// src/main/scala/camp/Core.scala:8:7, :52:27
        mem_reg_wb_addr = _RANDOM[5'hE][4:0];	// src/main/scala/camp/Core.scala:8:7, :53:32
        mem_reg_op1_data = {_RANDOM[5'hE][31:5], _RANDOM[5'hF][4:0]};	// src/main/scala/camp/Core.scala:8:7, :53:32, :54:33
        mem_reg_rs2_data = {_RANDOM[5'hF][31:5], _RANDOM[5'h10][4:0]};	// src/main/scala/camp/Core.scala:8:7, :54:33, :55:33
        mem_reg_mem_wen = _RANDOM[5'h10][6:5];	// src/main/scala/camp/Core.scala:8:7, :55:33, :56:32
        mem_reg_rf_wen = _RANDOM[5'h10][8:7];	// src/main/scala/camp/Core.scala:8:7, :55:33, :57:31
        mem_reg_wb_sel = _RANDOM[5'h10][11:9];	// src/main/scala/camp/Core.scala:8:7, :55:33, :58:31
        mem_reg_csr_addr = _RANDOM[5'h10][23:12];	// src/main/scala/camp/Core.scala:8:7, :55:33, :59:33
        mem_reg_csr_cmd = _RANDOM[5'h10][26:24];	// src/main/scala/camp/Core.scala:8:7, :55:33, :60:32
        mem_reg_alu_out = {_RANDOM[5'h11][31:27], _RANDOM[5'h12][26:0]};	// src/main/scala/camp/Core.scala:8:7, :62:32
        mem_reg_mem_w = {_RANDOM[5'h12][31:27], _RANDOM[5'h13][26:0]};	// src/main/scala/camp/Core.scala:8:7, :62:32, :63:30
        mem_reg_mem_wstrb = _RANDOM[5'h13][30:27];	// src/main/scala/camp/Core.scala:8:7, :63:30, :64:34
        wb_reg_wb_addr = {_RANDOM[5'h13][31], _RANDOM[5'h14][3:0]};	// src/main/scala/camp/Core.scala:8:7, :63:30, :67:31
        wb_reg_rf_wen = _RANDOM[5'h14][5:4];	// src/main/scala/camp/Core.scala:8:7, :67:31, :68:30
        wb_reg_wb_data = {_RANDOM[5'h14][31:6], _RANDOM[5'h15][5:0]};	// src/main/scala/camp/Core.scala:8:7, :67:31, :69:31
        if_reg_pc = {_RANDOM[5'h15][31:6], _RANDOM[5'h16][5:0]};	// src/main/scala/camp/Core.scala:8:7, :69:31, :74:26
        successDetected = _RANDOM[5'h16][6];	// src/main/scala/camp/Core.scala:8:7, :74:26, :590:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/camp/Core.scala:8:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/camp/Core.scala:8:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  regfile_32x32 regfile_ext (	// src/main/scala/camp/Core.scala:22:20
    .R0_addr (id_inst[24:20]),	// src/main/scala/camp/Core.scala:126:8, :129:28
    .R0_en   (1'h1),	// src/main/scala/camp/Core.scala:8:7
    .R0_clk  (clock),
    .R0_data (_regfile_ext_R0_data),
    .R1_addr (id_inst[19:15]),	// src/main/scala/camp/Core.scala:126:8, :128:28
    .R1_en   (1'h1),	// src/main/scala/camp/Core.scala:8:7
    .R1_clk  (clock),
    .R1_data (_regfile_ext_R1_data),
    .W0_addr (wb_reg_wb_addr),	// src/main/scala/camp/Core.scala:67:31
    .W0_en   (_id_rs2_data_T_5),	// src/main/scala/camp/Core.scala:138:59
    .W0_clk  (clock),
    .W0_data (wb_reg_wb_data)	// src/main/scala/camp/Core.scala:69:31
  );
  csr_regfile_4096x32 csr_regfile_ext (	// src/main/scala/camp/Core.scala:23:24
    .R0_addr (12'h305),	// src/main/scala/camp/Core.scala:92:41
    .R0_en   (1'h1),	// src/main/scala/camp/Core.scala:8:7
    .R0_clk  (clock),
    .R0_data (_csr_regfile_ext_R0_data),
    .R1_addr (mem_reg_csr_addr),	// src/main/scala/camp/Core.scala:59:33
    .R1_en   (1'h1),	// src/main/scala/camp/Core.scala:8:7
    .R1_clk  (clock),
    .R1_data (_csr_regfile_ext_R1_data),
    .W0_addr (mem_reg_csr_addr),	// src/main/scala/camp/Core.scala:59:33
    .W0_en   (|mem_reg_csr_cmd),	// src/main/scala/camp/Core.scala:60:32, :532:24
    .W0_clk  (clock),
    .W0_data
      (mem_reg_csr_cmd == 3'h1
         ? mem_reg_op1_data
         : mem_reg_csr_cmd == 3'h2
             ? _csr_regfile_ext_R1_data | mem_reg_op1_data
             : mem_reg_csr_cmd == 3'h3
                 ? _csr_regfile_ext_R1_data & ~mem_reg_op1_data
                 : mem_reg_csr_cmd == 3'h4 ? 32'hB : 32'h0)	// src/main/scala/camp/Core.scala:23:24, :29:26, :54:33, :60:32, :525:24, :526:{24,49}, :527:{24,49,51}, :528:24, src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/chisel3/util/Mux.scala:126:16
  );
  assign io_imem_addr = if_reg_pc;	// src/main/scala/camp/Core.scala:8:7, :74:26
  assign io_dmem_addr = mem_reg_alu_out;	// src/main/scala/camp/Core.scala:8:7, :62:32
  assign io_dmem_ren = io_dmem_ren_0;	// src/main/scala/camp/Core.scala:8:7, :509:33
  assign io_dmem_wen = mem_reg_mem_wen[0];	// src/main/scala/camp/Core.scala:8:7, :56:32, :510:15
  assign io_dmem_wstrb = mem_reg_mem_wstrb;	// src/main/scala/camp/Core.scala:8:7, :64:34
  assign io_dmem_wdata = _io_dmem_wdata_T_2[31:0];	// src/main/scala/camp/Core.scala:8:7, :512:{38,71}
  assign io_success = successDetected;	// src/main/scala/camp/Core.scala:8:7, :590:32
  assign io_exit = if_inst == 32'h73;	// src/main/scala/camp/Core.scala:8:7, :76:20, :92:16, :597:22
  assign io_debug_pc = if_reg_pc;	// src/main/scala/camp/Core.scala:8:7, :74:26
endmodule

module DMemDecoder(	// src/main/scala/camp/decoder.scala:7:7
  input  [31:0] io_initiator_addr,	// src/main/scala/camp/decoder.scala:8:14
  output [31:0] io_initiator_rdata,	// src/main/scala/camp/decoder.scala:8:14
  input         io_initiator_ren,	// src/main/scala/camp/decoder.scala:8:14
  output        io_initiator_rvalid,	// src/main/scala/camp/decoder.scala:8:14
  input         io_initiator_wen,	// src/main/scala/camp/decoder.scala:8:14
  input  [3:0]  io_initiator_wstrb,	// src/main/scala/camp/decoder.scala:8:14
  input  [31:0] io_initiator_wdata,	// src/main/scala/camp/decoder.scala:8:14
  output [31:0] io_targets_0_addr,	// src/main/scala/camp/decoder.scala:8:14
  input  [31:0] io_targets_0_rdata,	// src/main/scala/camp/decoder.scala:8:14
  output        io_targets_0_ren,	// src/main/scala/camp/decoder.scala:8:14
  input         io_targets_0_rvalid,	// src/main/scala/camp/decoder.scala:8:14
  output        io_targets_0_wen,	// src/main/scala/camp/decoder.scala:8:14
  output [3:0]  io_targets_0_wstrb,	// src/main/scala/camp/decoder.scala:8:14
  output [31:0] io_targets_0_wdata,	// src/main/scala/camp/decoder.scala:8:14
                io_targets_1_addr,	// src/main/scala/camp/decoder.scala:8:14
  input  [31:0] io_targets_1_rdata,	// src/main/scala/camp/decoder.scala:8:14
  output        io_targets_1_wen,	// src/main/scala/camp/decoder.scala:8:14
  output [3:0]  io_targets_1_wstrb,	// src/main/scala/camp/decoder.scala:8:14
  output [31:0] io_targets_1_wdata,	// src/main/scala/camp/decoder.scala:8:14
  input         io_targets_2_rvalid,	// src/main/scala/camp/decoder.scala:8:14
  output        io_targets_2_wen,	// src/main/scala/camp/decoder.scala:8:14
  output [31:0] io_targets_2_wdata	// src/main/scala/camp/decoder.scala:8:14
);

  wire _GEN = io_initiator_addr < 32'h2000;	// src/main/scala/camp/decoder.scala:36:57
  wire _GEN_0 = io_initiator_addr > 32'h9FFFFFFF & io_initiator_addr < 32'hA0000040;	// src/main/scala/camp/decoder.scala:36:{15,36,57}
  wire _GEN_1 = io_initiator_addr > 32'hAFFFFFFF & io_initiator_addr < 32'hB0000040;	// src/main/scala/camp/decoder.scala:36:{15,36,57}
  assign io_initiator_rdata =
    _GEN_1
      ? 32'hDEADBEEF
      : _GEN_0 ? io_targets_1_rdata : _GEN ? io_targets_0_rdata : 32'hDEADBEEF;	// src/main/scala/camp/decoder.scala:7:7, :8:14, :14:26, :36:{36,57}, :37:7, :41:13
  assign io_initiator_rvalid =
    _GEN_1 ? io_targets_2_rvalid : _GEN_0 | ~_GEN | io_targets_0_rvalid;	// src/main/scala/camp/decoder.scala:7:7, :13:27, :36:{36,57}, :37:7, :40:14
  assign io_targets_0_addr = _GEN ? io_initiator_addr : 32'h0;	// src/main/scala/camp/decoder.scala:7:7, :23:27, :36:57, :37:7, :38:12
  assign io_targets_0_ren = _GEN & io_initiator_ren;	// src/main/scala/camp/decoder.scala:7:7, :24:26, :36:57, :37:7, :39:11
  assign io_targets_0_wen = _GEN & io_initiator_wen;	// src/main/scala/camp/decoder.scala:7:7, :25:26, :36:57, :37:7, :42:11
  assign io_targets_0_wstrb = _GEN ? io_initiator_wstrb : 4'hF;	// src/main/scala/camp/decoder.scala:7:7, :27:28, :36:57, :37:7, :44:13
  assign io_targets_0_wdata = _GEN ? io_initiator_wdata : 32'hDEADBEEF;	// src/main/scala/camp/decoder.scala:7:7, :8:14, :26:28, :36:57, :37:7, :43:13
  assign io_targets_1_addr = _GEN_0 ? io_initiator_addr + 32'h60000000 : 32'h0;	// src/main/scala/camp/decoder.scala:7:7, :23:27, :36:36, :37:7, :38:{12,33}
  assign io_targets_1_wen = _GEN_0 & io_initiator_wen;	// src/main/scala/camp/decoder.scala:7:7, :25:26, :36:36, :37:7, :42:11
  assign io_targets_1_wstrb = _GEN_0 ? io_initiator_wstrb : 4'hF;	// src/main/scala/camp/decoder.scala:7:7, :27:28, :36:36, :37:7, :44:13
  assign io_targets_1_wdata = _GEN_0 ? io_initiator_wdata : 32'hDEADBEEF;	// src/main/scala/camp/decoder.scala:7:7, :8:14, :26:28, :36:36, :37:7, :43:13
  assign io_targets_2_wen = _GEN_1 & io_initiator_wen;	// src/main/scala/camp/decoder.scala:7:7, :25:26, :36:36, :37:7, :42:11
  assign io_targets_2_wdata = _GEN_1 ? io_initiator_wdata : 32'hDEADBEEF;	// src/main/scala/camp/decoder.scala:7:7, :8:14, :26:28, :36:36, :37:7, :43:13
endmodule

module Gpio(	// src/main/scala/camp/gpio.scala:7:7
  input         clock,	// src/main/scala/camp/gpio.scala:7:7
                reset,	// src/main/scala/camp/gpio.scala:7:7
  input  [31:0] io_mem_addr,	// src/main/scala/camp/gpio.scala:8:14
  output [31:0] io_mem_rdata,	// src/main/scala/camp/gpio.scala:8:14
  input         io_mem_wen,	// src/main/scala/camp/gpio.scala:8:14
  input  [3:0]  io_mem_wstrb,	// src/main/scala/camp/gpio.scala:8:14
  input  [31:0] io_mem_wdata,	// src/main/scala/camp/gpio.scala:8:14
  output [31:0] io_out	// src/main/scala/camp/gpio.scala:8:14
);

  reg  [31:0] out;	// src/main/scala/camp/gpio.scala:13:20
  wire [31:0] mask =
    {{8{io_mem_wstrb[3]}},
     {8{io_mem_wstrb[2]}},
     {8{io_mem_wstrb[1]}},
     {8{io_mem_wstrb[0]}}};	// src/main/scala/camp/gpio.scala:25:19, :26:{28,41}
  always @(posedge clock) begin	// src/main/scala/camp/gpio.scala:7:7
    if (reset)	// src/main/scala/camp/gpio.scala:7:7
      out <= 32'h0;	// src/main/scala/camp/gpio.scala:13:20
    else if (io_mem_wen & ~(|(io_mem_addr[3:2])))	// src/main/scala/camp/gpio.scala:13:20, :19:{40,62}, :24:20, :28:31, :31:13
      out <= out & ~mask | io_mem_wdata & mask;	// src/main/scala/camp/gpio.scala:13:20, :25:19, :31:{21,23,30,46}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/camp/gpio.scala:7:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/gpio.scala:7:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/gpio.scala:7:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/camp/gpio.scala:7:7
    initial begin	// src/main/scala/camp/gpio.scala:7:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/camp/gpio.scala:7:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/camp/gpio.scala:7:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/gpio.scala:7:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/camp/gpio.scala:7:7
        out = _RANDOM[/*Zero width*/ 1'b0];	// src/main/scala/camp/gpio.scala:7:7, :13:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/camp/gpio.scala:7:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/camp/gpio.scala:7:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_rdata = (|(io_mem_addr[3:2])) ? 32'hDEADBEEF : out;	// src/main/scala/camp/gpio.scala:7:7, :13:20, :17:16, :19:{40,62}
  assign io_out = out;	// src/main/scala/camp/gpio.scala:7:7, :13:20
endmodule

module LedMatrix(	// src/main/scala/camp/LEDmatrix.scala:46:7
  input         clock,	// src/main/scala/camp/LEDmatrix.scala:46:7
                reset,	// src/main/scala/camp/LEDmatrix.scala:46:7
  output        io_mem_rvalid,	// src/main/scala/camp/LEDmatrix.scala:47:14
  input         io_mem_wen,	// src/main/scala/camp/LEDmatrix.scala:47:14
  input  [31:0] io_mem_wdata,	// src/main/scala/camp/LEDmatrix.scala:47:14
  output [7:0]  io_anodes,	// src/main/scala/camp/LEDmatrix.scala:47:14
                io_cathodes	// src/main/scala/camp/LEDmatrix.scala:47:14
);

  reg  [7:0]  anodes;	// src/main/scala/camp/LEDmatrix.scala:53:23
  reg  [7:0]  cathodes;	// src/main/scala/camp/LEDmatrix.scala:54:25
  reg  [19:0] refleshCounter;	// src/main/scala/camp/LEDmatrix.scala:56:31
  reg  [2:0]  rowCounter;	// src/main/scala/camp/LEDmatrix.scala:57:27
  wire        _GEN = refleshCounter == 20'h0;	// src/main/scala/camp/LEDmatrix.scala:56:31, :71:23
  wire        _GEN_0 = rowCounter == 3'h0;	// src/main/scala/camp/LEDmatrix.scala:57:27, :74:21
  always @(posedge clock) begin	// src/main/scala/camp/LEDmatrix.scala:46:7
    if (reset) begin	// src/main/scala/camp/LEDmatrix.scala:46:7
      anodes <= 8'h1;	// src/main/scala/camp/LEDmatrix.scala:53:23
      cathodes <= 8'h1;	// src/main/scala/camp/LEDmatrix.scala:53:23, :54:25
      refleshCounter <= 20'h0;	// src/main/scala/camp/LEDmatrix.scala:56:31
      rowCounter <= 3'h0;	// src/main/scala/camp/LEDmatrix.scala:57:27
    end
    else begin	// src/main/scala/camp/LEDmatrix.scala:46:7
      if (io_mem_wen)	// src/main/scala/camp/LEDmatrix.scala:47:14
        anodes <= io_mem_wdata[15:8];	// src/main/scala/camp/LEDmatrix.scala:53:23, :67:27
      if (_GEN & _GEN_0) begin	// src/main/scala/camp/LEDmatrix.scala:54:25, :71:{23,32}, :74:{21,30}, :75:16
        if (cathodes == 8'h1)	// src/main/scala/camp/LEDmatrix.scala:53:23, :54:25, :75:32
          cathodes <= 8'h80;	// src/main/scala/camp/LEDmatrix.scala:54:25, :75:22
        else	// src/main/scala/camp/LEDmatrix.scala:75:32
          cathodes <= {1'h0, cathodes[7:1]};	// src/main/scala/camp/LEDmatrix.scala:46:7, :54:25, :75:{22,57}
      end
      if (_GEN) begin	// src/main/scala/camp/LEDmatrix.scala:71:23
        refleshCounter <= 20'hF423F;	// src/main/scala/camp/LEDmatrix.scala:56:31, :72:20
        if (_GEN_0)	// src/main/scala/camp/LEDmatrix.scala:74:21
          rowCounter <= 3'h0;	// src/main/scala/camp/LEDmatrix.scala:57:27
        else	// src/main/scala/camp/LEDmatrix.scala:74:21
          rowCounter <= rowCounter - 3'h1;	// src/main/scala/camp/LEDmatrix.scala:57:27, :80:32
      end
      else	// src/main/scala/camp/LEDmatrix.scala:71:23
        refleshCounter <= refleshCounter - 20'h1;	// src/main/scala/camp/LEDmatrix.scala:56:31, :83:38
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/camp/LEDmatrix.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/LEDmatrix.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/LEDmatrix.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// src/main/scala/camp/LEDmatrix.scala:46:7
    initial begin	// src/main/scala/camp/LEDmatrix.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/camp/LEDmatrix.scala:46:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/camp/LEDmatrix.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/LEDmatrix.scala:46:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// src/main/scala/camp/LEDmatrix.scala:46:7
        end	// src/main/scala/camp/LEDmatrix.scala:46:7
        anodes = _RANDOM[1'h0][7:0];	// src/main/scala/camp/LEDmatrix.scala:46:7, :53:23
        cathodes = _RANDOM[1'h0][15:8];	// src/main/scala/camp/LEDmatrix.scala:46:7, :53:23, :54:25
        refleshCounter = {_RANDOM[1'h0][31:16], _RANDOM[1'h1][3:0]};	// src/main/scala/camp/LEDmatrix.scala:46:7, :53:23, :56:31
        rowCounter = _RANDOM[1'h1][6:4];	// src/main/scala/camp/LEDmatrix.scala:46:7, :56:31, :57:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/camp/LEDmatrix.scala:46:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/camp/LEDmatrix.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_rvalid = ~io_mem_wen;	// src/main/scala/camp/LEDmatrix.scala:46:7, :64:17, :66:20, :68:19
  assign io_anodes = anodes;	// src/main/scala/camp/LEDmatrix.scala:46:7, :53:23
  assign io_cathodes = ~cathodes;	// src/main/scala/camp/LEDmatrix.scala:46:7, :54:25, :61:18
endmodule

// VCS coverage exclude_file
module mems_0_2048x8(	// src/main/scala/camp/Memory.scala:34:43
  input  [10:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [7:0]  R0_data,
  input  [10:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [7:0]  R1_data,
  input  [10:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [7:0]  W0_data
);

  reg [7:0]  Memory[0:2047];	// src/main/scala/camp/Memory.scala:34:43
  reg        _R0_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R0_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R0_en_d0 <= R0_en;	// src/main/scala/camp/Memory.scala:34:43
    _R0_addr_d0 <= R0_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  reg        _R1_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R1_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R1_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R1_en_d0 <= R1_en;	// src/main/scala/camp/Memory.scala:34:43
    _R1_addr_d0 <= R1_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    if (W0_en & 1'h1)	// src/main/scala/camp/Memory.scala:34:43
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Memory.scala:34:43
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
      reg [31:0] _RANDOM;	// src/main/scala/camp/Memory.scala:34:43
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Memory.scala:34:43
    initial begin	// src/main/scala/camp/Memory.scala:34:43
      $readmemh("../sw/bootrom_0.hex", Memory);	// src/main/scala/camp/Memory.scala:34:43
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:34:43
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Memory.scala:34:43
        for (logic [11:0] i = 12'h0; i < 12'h800; i += 12'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Memory.scala:34:43
          Memory[i[10:0]] = _RANDOM_MEM[7:0];	// src/main/scala/camp/Memory.scala:34:43
        end	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
        _RANDOM = {`RANDOM};	// src/main/scala/camp/Memory.scala:34:43
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/camp/Memory.scala:34:43
        _R0_addr_d0 = _RANDOM[11:1];	// src/main/scala/camp/Memory.scala:34:43
        _R1_en_d0 = _RANDOM[12];	// src/main/scala/camp/Memory.scala:34:43
        _R1_addr_d0 = _RANDOM[23:13];	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
endmodule

// VCS coverage exclude_file
module mems_1_2048x8(	// src/main/scala/camp/Memory.scala:34:43
  input  [10:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [7:0]  R0_data,
  input  [10:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [7:0]  R1_data,
  input  [10:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [7:0]  W0_data
);

  reg [7:0]  Memory[0:2047];	// src/main/scala/camp/Memory.scala:34:43
  reg        _R0_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R0_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R0_en_d0 <= R0_en;	// src/main/scala/camp/Memory.scala:34:43
    _R0_addr_d0 <= R0_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  reg        _R1_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R1_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R1_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R1_en_d0 <= R1_en;	// src/main/scala/camp/Memory.scala:34:43
    _R1_addr_d0 <= R1_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    if (W0_en & 1'h1)	// src/main/scala/camp/Memory.scala:34:43
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Memory.scala:34:43
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
      reg [31:0] _RANDOM;	// src/main/scala/camp/Memory.scala:34:43
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Memory.scala:34:43
    initial begin	// src/main/scala/camp/Memory.scala:34:43
      $readmemh("../sw/bootrom_1.hex", Memory);	// src/main/scala/camp/Memory.scala:34:43
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:34:43
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Memory.scala:34:43
        for (logic [11:0] i = 12'h0; i < 12'h800; i += 12'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Memory.scala:34:43
          Memory[i[10:0]] = _RANDOM_MEM[7:0];	// src/main/scala/camp/Memory.scala:34:43
        end	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
        _RANDOM = {`RANDOM};	// src/main/scala/camp/Memory.scala:34:43
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/camp/Memory.scala:34:43
        _R0_addr_d0 = _RANDOM[11:1];	// src/main/scala/camp/Memory.scala:34:43
        _R1_en_d0 = _RANDOM[12];	// src/main/scala/camp/Memory.scala:34:43
        _R1_addr_d0 = _RANDOM[23:13];	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
endmodule

// VCS coverage exclude_file
module mems_2_2048x8(	// src/main/scala/camp/Memory.scala:34:43
  input  [10:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [7:0]  R0_data,
  input  [10:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [7:0]  R1_data,
  input  [10:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [7:0]  W0_data
);

  reg [7:0]  Memory[0:2047];	// src/main/scala/camp/Memory.scala:34:43
  reg        _R0_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R0_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R0_en_d0 <= R0_en;	// src/main/scala/camp/Memory.scala:34:43
    _R0_addr_d0 <= R0_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  reg        _R1_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R1_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R1_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R1_en_d0 <= R1_en;	// src/main/scala/camp/Memory.scala:34:43
    _R1_addr_d0 <= R1_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    if (W0_en & 1'h1)	// src/main/scala/camp/Memory.scala:34:43
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Memory.scala:34:43
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
      reg [31:0] _RANDOM;	// src/main/scala/camp/Memory.scala:34:43
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Memory.scala:34:43
    initial begin	// src/main/scala/camp/Memory.scala:34:43
      $readmemh("../sw/bootrom_2.hex", Memory);	// src/main/scala/camp/Memory.scala:34:43
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:34:43
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Memory.scala:34:43
        for (logic [11:0] i = 12'h0; i < 12'h800; i += 12'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Memory.scala:34:43
          Memory[i[10:0]] = _RANDOM_MEM[7:0];	// src/main/scala/camp/Memory.scala:34:43
        end	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
        _RANDOM = {`RANDOM};	// src/main/scala/camp/Memory.scala:34:43
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/camp/Memory.scala:34:43
        _R0_addr_d0 = _RANDOM[11:1];	// src/main/scala/camp/Memory.scala:34:43
        _R1_en_d0 = _RANDOM[12];	// src/main/scala/camp/Memory.scala:34:43
        _R1_addr_d0 = _RANDOM[23:13];	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
endmodule

// VCS coverage exclude_file
module mems_3_2048x8(	// src/main/scala/camp/Memory.scala:34:43
  input  [10:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [7:0]  R0_data,
  input  [10:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [7:0]  R1_data,
  input  [10:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [7:0]  W0_data
);

  reg [7:0]  Memory[0:2047];	// src/main/scala/camp/Memory.scala:34:43
  reg        _R0_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R0_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R0_en_d0 <= R0_en;	// src/main/scala/camp/Memory.scala:34:43
    _R0_addr_d0 <= R0_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  reg        _R1_en_d0;	// src/main/scala/camp/Memory.scala:34:43
  reg [10:0] _R1_addr_d0;	// src/main/scala/camp/Memory.scala:34:43
  always @(posedge R1_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    _R1_en_d0 <= R1_en;	// src/main/scala/camp/Memory.scala:34:43
    _R1_addr_d0 <= R1_addr;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/camp/Memory.scala:34:43
    if (W0_en & 1'h1)	// src/main/scala/camp/Memory.scala:34:43
      Memory[W0_addr] <= W0_data;	// src/main/scala/camp/Memory.scala:34:43
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/camp/Memory.scala:34:43
    `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
      reg [31:0] _RANDOM;	// src/main/scala/camp/Memory.scala:34:43
    `endif // RANDOMIZE_REG_INIT
    reg [31:0] _RANDOM_MEM;	// src/main/scala/camp/Memory.scala:34:43
    initial begin	// src/main/scala/camp/Memory.scala:34:43
      $readmemh("../sw/bootrom_3.hex", Memory);	// src/main/scala/camp/Memory.scala:34:43
      `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:34:43
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/camp/Memory.scala:34:43
        for (logic [11:0] i = 12'h0; i < 12'h800; i += 12'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/camp/Memory.scala:34:43
          Memory[i[10:0]] = _RANDOM_MEM[7:0];	// src/main/scala/camp/Memory.scala:34:43
        end	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:34:43
        _RANDOM = {`RANDOM};	// src/main/scala/camp/Memory.scala:34:43
        _R0_en_d0 = _RANDOM[0];	// src/main/scala/camp/Memory.scala:34:43
        _R0_addr_d0 = _RANDOM[11:1];	// src/main/scala/camp/Memory.scala:34:43
        _R1_en_d0 = _RANDOM[12];	// src/main/scala/camp/Memory.scala:34:43
        _R1_addr_d0 = _RANDOM[23:13];	// src/main/scala/camp/Memory.scala:34:43
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
  assign R1_data = _R1_en_d0 ? Memory[_R1_addr_d0] : 8'bx;	// src/main/scala/camp/Memory.scala:34:43
endmodule

module Memory(	// src/main/scala/camp/Memory.scala:24:7
  input         clock,	// src/main/scala/camp/Memory.scala:24:7
                reset,	// src/main/scala/camp/Memory.scala:24:7
  input  [31:0] io_imem_addr,	// src/main/scala/camp/Memory.scala:29:14
  output [31:0] io_imem_inst,	// src/main/scala/camp/Memory.scala:29:14
  output        io_imem_valid,	// src/main/scala/camp/Memory.scala:29:14
  input  [31:0] io_dmem_addr,	// src/main/scala/camp/Memory.scala:29:14
  output [31:0] io_dmem_rdata,	// src/main/scala/camp/Memory.scala:29:14
  input         io_dmem_ren,	// src/main/scala/camp/Memory.scala:29:14
  output        io_dmem_rvalid,	// src/main/scala/camp/Memory.scala:29:14
  input         io_dmem_wen,	// src/main/scala/camp/Memory.scala:29:14
  input  [3:0]  io_dmem_wstrb,	// src/main/scala/camp/Memory.scala:29:14
  input  [31:0] io_dmem_wdata	// src/main/scala/camp/Memory.scala:29:14
);

  wire [7:0]  _mems_3_ext_R0_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_3_ext_R1_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_2_ext_R0_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_2_ext_R1_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_1_ext_R0_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_1_ext_R1_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_0_ext_R0_data;	// src/main/scala/camp/Memory.scala:34:43
  wire [7:0]  _mems_0_ext_R1_data;	// src/main/scala/camp/Memory.scala:34:43
  reg  [29:0] imemWordAddrFetched;	// src/main/scala/camp/Memory.scala:43:32
  reg         isFirstCycle;	// src/main/scala/camp/Memory.scala:44:29
  reg         rvalid;	// src/main/scala/camp/Memory.scala:54:23
  wire [31:0] rdata =
    {_mems_3_ext_R0_data, _mems_2_ext_R0_data, _mems_1_ext_R0_data, _mems_0_ext_R0_data};	// src/main/scala/camp/Memory.scala:34:43, :55:18
  reg  [31:0] dmemAddrReg;	// src/main/scala/camp/Memory.scala:61:24
  `ifndef SYNTHESIS	// src/main/scala/camp/Memory.scala:67:11
    always @(posedge clock) begin	// src/main/scala/camp/Memory.scala:67:11
      if ((`PRINTF_COND_) & rvalid & ~reset)	// src/main/scala/camp/Memory.scala:54:23, :67:11
        $fwrite(32'h80000002, "Data read address=0x%x data=0x%x\n", dmemAddrReg, rdata);	// src/main/scala/camp/Memory.scala:55:18, :61:24, :67:11
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _GEN = io_dmem_ren & ~io_dmem_wen & ~rvalid;	// src/main/scala/camp/Memory.scala:54:23, :62:{23,36,39}
  always @(posedge clock) begin	// src/main/scala/camp/Memory.scala:24:7
    imemWordAddrFetched <= io_imem_addr[31:2];	// src/main/scala/camp/Memory.scala:42:51, :43:32
    if (_GEN)	// src/main/scala/camp/Memory.scala:62:36
      dmemAddrReg <= io_dmem_addr;	// src/main/scala/camp/Memory.scala:61:24
    if (reset) begin	// src/main/scala/camp/Memory.scala:24:7
      isFirstCycle <= 1'h1;	// src/main/scala/camp/Memory.scala:24:7, :44:29
      rvalid <= 1'h0;	// src/main/scala/camp/Memory.scala:24:7, :54:23
    end
    else begin	// src/main/scala/camp/Memory.scala:24:7
      isFirstCycle <= 1'h0;	// src/main/scala/camp/Memory.scala:24:7, :44:29
      rvalid <= _GEN;	// src/main/scala/camp/Memory.scala:54:23, :62:36
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/camp/Memory.scala:24:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/Memory.scala:24:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/camp/Memory.scala:24:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// src/main/scala/camp/Memory.scala:24:7
    initial begin	// src/main/scala/camp/Memory.scala:24:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:24:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/camp/Memory.scala:24:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/camp/Memory.scala:24:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// src/main/scala/camp/Memory.scala:24:7
        end	// src/main/scala/camp/Memory.scala:24:7
        imemWordAddrFetched = _RANDOM[1'h0][29:0];	// src/main/scala/camp/Memory.scala:24:7, :43:32
        isFirstCycle = _RANDOM[1'h0][30];	// src/main/scala/camp/Memory.scala:24:7, :43:32, :44:29
        rvalid = _RANDOM[1'h0][31];	// src/main/scala/camp/Memory.scala:24:7, :43:32, :54:23
        dmemAddrReg = _RANDOM[1'h1];	// src/main/scala/camp/Memory.scala:24:7, :61:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/camp/Memory.scala:24:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/camp/Memory.scala:24:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  mems_0_2048x8 mems_0_ext (	// src/main/scala/camp/Memory.scala:34:43
    .R0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:56:35
    .R0_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R0_clk  (clock),
    .R0_data (_mems_0_ext_R0_data),
    .R1_addr (io_imem_addr[12:2]),	// src/main/scala/camp/Memory.scala:50:35
    .R1_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R1_clk  (clock),
    .R1_data (_mems_0_ext_R1_data),
    .W0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:74:22, :75:40
    .W0_en   (io_dmem_wen & io_dmem_wstrb[0]),	// src/main/scala/camp/Memory.scala:34:43, :71:21, :73:{25,30}
    .W0_clk  (clock),
    .W0_data (io_dmem_wdata[7:0])	// src/main/scala/camp/Memory.scala:76:24
  );
  mems_1_2048x8 mems_1_ext (	// src/main/scala/camp/Memory.scala:34:43
    .R0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:56:35
    .R0_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R0_clk  (clock),
    .R0_data (_mems_1_ext_R0_data),
    .R1_addr (io_imem_addr[12:2]),	// src/main/scala/camp/Memory.scala:50:35
    .R1_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R1_clk  (clock),
    .R1_data (_mems_1_ext_R1_data),
    .W0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:74:22, :75:40
    .W0_en   (io_dmem_wen & io_dmem_wstrb[1]),	// src/main/scala/camp/Memory.scala:34:43, :71:21, :73:{25,30}
    .W0_clk  (clock),
    .W0_data (io_dmem_wdata[15:8])	// src/main/scala/camp/Memory.scala:76:24
  );
  mems_2_2048x8 mems_2_ext (	// src/main/scala/camp/Memory.scala:34:43
    .R0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:56:35
    .R0_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R0_clk  (clock),
    .R0_data (_mems_2_ext_R0_data),
    .R1_addr (io_imem_addr[12:2]),	// src/main/scala/camp/Memory.scala:50:35
    .R1_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R1_clk  (clock),
    .R1_data (_mems_2_ext_R1_data),
    .W0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:74:22, :75:40
    .W0_en   (io_dmem_wen & io_dmem_wstrb[2]),	// src/main/scala/camp/Memory.scala:34:43, :71:21, :73:{25,30}
    .W0_clk  (clock),
    .W0_data (io_dmem_wdata[23:16])	// src/main/scala/camp/Memory.scala:76:24
  );
  mems_3_2048x8 mems_3_ext (	// src/main/scala/camp/Memory.scala:34:43
    .R0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:56:35
    .R0_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R0_clk  (clock),
    .R0_data (_mems_3_ext_R0_data),
    .R1_addr (io_imem_addr[12:2]),	// src/main/scala/camp/Memory.scala:50:35
    .R1_en   (1'h1),	// src/main/scala/camp/Memory.scala:24:7
    .R1_clk  (clock),
    .R1_data (_mems_3_ext_R1_data),
    .W0_addr (io_dmem_addr[12:2]),	// src/main/scala/camp/Memory.scala:74:22, :75:40
    .W0_en   (io_dmem_wen & io_dmem_wstrb[3]),	// src/main/scala/camp/Memory.scala:34:43, :71:21, :73:{25,30}
    .W0_clk  (clock),
    .W0_data (io_dmem_wdata[31:24])	// src/main/scala/camp/Memory.scala:76:24
  );
  assign io_imem_inst =
    {_mems_3_ext_R1_data, _mems_2_ext_R1_data, _mems_1_ext_R1_data, _mems_0_ext_R1_data};	// src/main/scala/camp/Memory.scala:24:7, :34:43, :49:22
  assign io_imem_valid = ~isFirstCycle & imemWordAddrFetched == io_imem_addr[31:2];	// src/main/scala/camp/Memory.scala:24:7, :42:51, :43:32, :44:29, :47:{20,34,57}
  assign io_dmem_rdata = rdata;	// src/main/scala/camp/Memory.scala:24:7, :55:18
  assign io_dmem_rvalid = rvalid;	// src/main/scala/camp/Memory.scala:24:7, :54:23
endmodule

module Top(	// src/main/scala/camp/Top.scala:6:7
  input         clock,	// src/main/scala/camp/Top.scala:6:7
                reset,	// src/main/scala/camp/Top.scala:6:7
  output        io_exit,	// src/main/scala/camp/Top.scala:7:14
  output [31:0] io_debug_pc,	// src/main/scala/camp/Top.scala:7:14
                io_gpio_out,	// src/main/scala/camp/Top.scala:7:14
  output [7:0]  io_anodes,	// src/main/scala/camp/Top.scala:7:14
                io_cathodes,	// src/main/scala/camp/Top.scala:7:14
  output        io_success,	// src/main/scala/camp/Top.scala:7:14
  input         io_uart_rx	// src/main/scala/camp/Top.scala:7:14
);

  wire [31:0] _memory_io_imem_inst;	// src/main/scala/camp/Top.scala:40:22
  wire        _memory_io_imem_valid;	// src/main/scala/camp/Top.scala:40:22
  wire [31:0] _memory_io_dmem_rdata;	// src/main/scala/camp/Top.scala:40:22
  wire        _memory_io_dmem_rvalid;	// src/main/scala/camp/Top.scala:40:22
  wire        _ledMatrix_io_mem_rvalid;	// src/main/scala/camp/Top.scala:36:25
  wire [31:0] _gpio_io_mem_rdata;	// src/main/scala/camp/Top.scala:31:20
  wire [31:0] _decoder_io_initiator_rdata;	// src/main/scala/camp/Top.scala:21:23
  wire        _decoder_io_initiator_rvalid;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _decoder_io_targets_0_addr;	// src/main/scala/camp/Top.scala:21:23
  wire        _decoder_io_targets_0_ren;	// src/main/scala/camp/Top.scala:21:23
  wire        _decoder_io_targets_0_wen;	// src/main/scala/camp/Top.scala:21:23
  wire [3:0]  _decoder_io_targets_0_wstrb;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _decoder_io_targets_0_wdata;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _decoder_io_targets_1_addr;	// src/main/scala/camp/Top.scala:21:23
  wire        _decoder_io_targets_1_wen;	// src/main/scala/camp/Top.scala:21:23
  wire [3:0]  _decoder_io_targets_1_wstrb;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _decoder_io_targets_1_wdata;	// src/main/scala/camp/Top.scala:21:23
  wire        _decoder_io_targets_2_wen;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _decoder_io_targets_2_wdata;	// src/main/scala/camp/Top.scala:21:23
  wire [31:0] _core_io_imem_addr;	// src/main/scala/camp/Top.scala:20:20
  wire [31:0] _core_io_dmem_addr;	// src/main/scala/camp/Top.scala:20:20
  wire        _core_io_dmem_ren;	// src/main/scala/camp/Top.scala:20:20
  wire        _core_io_dmem_wen;	// src/main/scala/camp/Top.scala:20:20
  wire [3:0]  _core_io_dmem_wstrb;	// src/main/scala/camp/Top.scala:20:20
  wire [31:0] _core_io_dmem_wdata;	// src/main/scala/camp/Top.scala:20:20
  Core core (	// src/main/scala/camp/Top.scala:20:20
    .clock          (clock),
    .reset          (reset),
    .io_imem_addr   (_core_io_imem_addr),
    .io_imem_inst   (_memory_io_imem_inst),	// src/main/scala/camp/Top.scala:40:22
    .io_imem_valid  (_memory_io_imem_valid),	// src/main/scala/camp/Top.scala:40:22
    .io_dmem_addr   (_core_io_dmem_addr),
    .io_dmem_rdata  (_decoder_io_initiator_rdata),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_ren    (_core_io_dmem_ren),
    .io_dmem_rvalid (_decoder_io_initiator_rvalid),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_wen    (_core_io_dmem_wen),
    .io_dmem_wstrb  (_core_io_dmem_wstrb),
    .io_dmem_wdata  (_core_io_dmem_wdata),
    .io_success     (io_success),
    .io_exit        (io_exit),
    .io_debug_pc    (io_debug_pc)
  );
  DMemDecoder decoder (	// src/main/scala/camp/Top.scala:21:23
    .io_initiator_addr   (_core_io_dmem_addr),	// src/main/scala/camp/Top.scala:20:20
    .io_initiator_rdata  (_decoder_io_initiator_rdata),
    .io_initiator_ren    (_core_io_dmem_ren),	// src/main/scala/camp/Top.scala:20:20
    .io_initiator_rvalid (_decoder_io_initiator_rvalid),
    .io_initiator_wen    (_core_io_dmem_wen),	// src/main/scala/camp/Top.scala:20:20
    .io_initiator_wstrb  (_core_io_dmem_wstrb),	// src/main/scala/camp/Top.scala:20:20
    .io_initiator_wdata  (_core_io_dmem_wdata),	// src/main/scala/camp/Top.scala:20:20
    .io_targets_0_addr   (_decoder_io_targets_0_addr),
    .io_targets_0_rdata  (_memory_io_dmem_rdata),	// src/main/scala/camp/Top.scala:40:22
    .io_targets_0_ren    (_decoder_io_targets_0_ren),
    .io_targets_0_rvalid (_memory_io_dmem_rvalid),	// src/main/scala/camp/Top.scala:40:22
    .io_targets_0_wen    (_decoder_io_targets_0_wen),
    .io_targets_0_wstrb  (_decoder_io_targets_0_wstrb),
    .io_targets_0_wdata  (_decoder_io_targets_0_wdata),
    .io_targets_1_addr   (_decoder_io_targets_1_addr),
    .io_targets_1_rdata  (_gpio_io_mem_rdata),	// src/main/scala/camp/Top.scala:31:20
    .io_targets_1_wen    (_decoder_io_targets_1_wen),
    .io_targets_1_wstrb  (_decoder_io_targets_1_wstrb),
    .io_targets_1_wdata  (_decoder_io_targets_1_wdata),
    .io_targets_2_rvalid (_ledMatrix_io_mem_rvalid),	// src/main/scala/camp/Top.scala:36:25
    .io_targets_2_wen    (_decoder_io_targets_2_wen),
    .io_targets_2_wdata  (_decoder_io_targets_2_wdata)
  );
  Gpio gpio (	// src/main/scala/camp/Top.scala:31:20
    .clock        (clock),
    .reset        (reset),
    .io_mem_addr  (_decoder_io_targets_1_addr),	// src/main/scala/camp/Top.scala:21:23
    .io_mem_rdata (_gpio_io_mem_rdata),
    .io_mem_wen   (_decoder_io_targets_1_wen),	// src/main/scala/camp/Top.scala:21:23
    .io_mem_wstrb (_decoder_io_targets_1_wstrb),	// src/main/scala/camp/Top.scala:21:23
    .io_mem_wdata (_decoder_io_targets_1_wdata),	// src/main/scala/camp/Top.scala:21:23
    .io_out       (io_gpio_out)
  );
  LedMatrix ledMatrix (	// src/main/scala/camp/Top.scala:36:25
    .clock         (clock),
    .reset         (reset),
    .io_mem_rvalid (_ledMatrix_io_mem_rvalid),
    .io_mem_wen    (_decoder_io_targets_2_wen),	// src/main/scala/camp/Top.scala:21:23
    .io_mem_wdata  (_decoder_io_targets_2_wdata),	// src/main/scala/camp/Top.scala:21:23
    .io_anodes     (io_anodes),
    .io_cathodes   (io_cathodes)
  );
  Memory memory (	// src/main/scala/camp/Top.scala:40:22
    .clock          (clock),
    .reset          (reset),
    .io_imem_addr   (_core_io_imem_addr),	// src/main/scala/camp/Top.scala:20:20
    .io_imem_inst   (_memory_io_imem_inst),
    .io_imem_valid  (_memory_io_imem_valid),
    .io_dmem_addr   (_decoder_io_targets_0_addr),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_rdata  (_memory_io_dmem_rdata),
    .io_dmem_ren    (_decoder_io_targets_0_ren),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_rvalid (_memory_io_dmem_rvalid),
    .io_dmem_wen    (_decoder_io_targets_0_wen),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_wstrb  (_decoder_io_targets_0_wstrb),	// src/main/scala/camp/Top.scala:21:23
    .io_dmem_wdata  (_decoder_io_targets_0_wdata)	// src/main/scala/camp/Top.scala:21:23
  );
endmodule

