name: Continuous Integration

on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build docker
        run: docker build -t chisel-riscv .
      - name: list
        run: ls
      - name: run docker test
        run: docker run -v ./src:/src chisel-riscv:latest sbt 'testOnly gcd.GCDSpec'
